#!/bin/bash

mkdir -p build_codeblocks && \
cd build_codeblocks && \
cmake -DCMAKE_BUILD_TYPE=Debug \
      -G "CodeBlocks - Unix Makefiles" \
      -DCMAKE_INSTALL_PREFIX:PATH=inst_cb ..

(nohup codeblocks *.cbp 2>/dev/null &)
sleep 1

